### ISSUE TITLE
One To One problem

### ISSUE THREAD

**Issue by ray1984** [greenrobot/greenDAO#190]
I created structure from two entiites: Customer and Shop. One customer can have only one shop, and one shop can be binded only with one customer. My code:
```
Entity shop = schema.addEntity("Shop");
shop.addIdProperty();
shop.addStringProperty("name");

Entity customer = schema.addEntity("Customer");
customer.addIdProperty();
customer.addStringProperty("name");

Property shopId = customer.addLongProperty("shopId").getProperty();
customer.addToOne(shop, shopId);

Property customerId = shop.addLongProperty("customerId").getProperty();
shop.addToOne(customer, customerId);
```

That's my example code for saving entities:
```
Shop shop = new Shop();
shop.setName("shop #1");
long shopId = daoSession.insert(shop);

Customer customer = new Customer();
customer.setName("customer #1");
customer.setShopId(shopId);
long customerId = daoSession.insert(customer);
```

When I read Customer by customerId the object has propery getShop. BUT when I read Shop by shopId getCustomer == null, but it must contain "customer 1"

**Comment by xiongmaozhijin** [comment]
Because it is To-one relationship, we should add mapping each other. Above code you post that hadn't add column value CUSTOMER_ID in ENTITY Shop. Therefore, it will return null when we use getCustomer, which getter function will create query sql statemnet and where conditions relative to column CUSTOMER_ID.
If we code like this, it will work:
```
...
long customerId = daoSession.insert(customer);
shop.setCustomerId(customerId);
daoSession.insertOrReplace(shop);
...
```
