### ISSUE TITLE
About close DataBase

### ISSUE THREAD

**Issue by nimengbo** [greenrobot/greenDAO#251]
Should I manually close database? or greenDao will close it automatically ?

**Comment by ipcjs** [comment]
Do not close the database

**Comment by nimengbo** [comment]
@ipcjs  why?

**Comment by Groxx** [comment]
Because closing the database tosses all the connection information, and re-building those is not a cheap operation.

There's no need to close the database ever in 99%+ of applications, and last I benchmarked it's over 100x faster to leave it open on small queries.  The database is already threadsafe and protected behind your SQLiteDatabase object - just use it.


On October 22, 2015 at 08:03:31, Abner (notifications@github.com) wrote:

@ipcjs why?

**Comment by nimengbo** [comment]
If do not close the database . locat will be print this : 
Leak found  
Caused by: java.lang.IllegalStateException: SQLiteDatabase created and never closed

**Comment by ipcjs** [comment]
@nimengbo Will not. At least my application did not report this warn.

**Comment by johnwatsondev** [comment]
@nimengbo I also meet this issue. What's your approach about close db?
