### ISSUE TITLE
Add To-One Bidirectional relations

### ISSUE THREAD

**Issue by ykobets** [greenrobot/greenDAO#263]
Can you add One-To-One bidirectional relation?
Declaring relation for one entity can be inverse accessable to other.
E.g. declaring Entity: Address. It has property Person. [Address].person = somePerson
And it gives us inverse access to [Person].address.

**Comment by yishai-glide** [comment]
there is already a very good example of this in the docs here: http://greendao-orm.com/documentation/relations/

**Comment by ykobets** [comment]
There is the example of one-to-many relation (Bi-Directional 1:N Relations).
I am looking for one-to-one inverse relation. This could be implemented with current 1:N relation. 

And I am asking could it be added as Property declaration without ToMany relation?

**Comment by rootandy** [comment]
I want to bring this ticket up again, because all bidirectional relations (To-One and To-Many) ability got lost in the update to greenDao 3. So I want to up this ticket and hope for implementing such a feature for at least one of them (To-one or To-Many) so with the annotations this would be possible. That would be great.

**Comment by greenrobot-team** [comment]
@rootandy You should be able to [replicate bi-directional relations](http://greenrobot.org/greendao/documentation/relations/#Bi-Directional_1N_Relations) by using 
- the `@ToOne` annotation instead of `.addToOne()` and
- the `@ToMany` annotation instead of `.addToMany()`.

[Examples in the v3 docs](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Relation_annotations_ToOne_ToMany_etc).

Does this not work for you, could you given an example? -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
