### ISSUE TITLE
DaoSession must be set during content provider is active

### ISSUE THREAD

**Issue by shawyou** [greenrobot/greenDAO#304]
My app sometimes get the error “DaoSession must be set during content provider is active”.
cann't Greendao inited in async thread?

**Comment by OmarHassan25** [comment]
Have you fixed this issue ? I am facing the same issue.

**Comment by greenrobot-team** [comment]
I suppose you have to set a value to `SimpleEntityContentProvider.daoSession` in your content provider `onCreate()`. Otherwise it will remain `null`.

Have a look at the [source of `SimpleEntityContentProvider`](https://github.com/greenrobot/greenDAO/blob/V2.1.0/DaoTest/src-gen/de/greenrobot/daotest/SimpleEntityContentProvider.java#L47-L51). Keep in mind though that greenDAO does not officially support content providers.
