### ISSUE TITLE
@ToMany has some error

### ISSUE THREAD

**Issue by crazecoder** [greenrobot/greenDAO#397]
my code
```java
 @ToMany(joinProperties = {
            @JoinProperty(name = "id", referencedName = "goodsId")
    })
    private List<GoodSpec> spec;
```
error
```
Error:Execution failed for task ':app:greendao'.
> Can't replace method in xx.java:82 with generated version.
                      If you would like to keep it, it should be explicitly marked with @Keep annotation.
                      Otherwise please mark it with @Generated annotation
```

**Comment by greenrobot-team** [comment]
The error message means you have modified one of the methods (the one in line 82) that was generated by greendao. If you did that on purpose, annotate it with `@Keep` so your changes are kept.

Otherwise annotate it with `@Generated` so greendao can properly replace it.

More info [in the docs](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Generated_Code).
-ut
