### ISSUE TITLE
gradle report error on @SuppressWarnings("WeakerAccess")

### ISSUE THREAD

**Issue by pzhangleo** [greenrobot/greenDAO#457]
class like this:
@SuppressWarnings("WeakerAccess")
@Entity
public class SessionModel implements BaseObject

**Comment by greenrobot-team** [comment]
Thanks for reporting! This is because our class parser does not support the `WeakerAccess` token for the `@SuppressWarnings` annotation.

Until we release a fix you can remove the annotation and instead turn off the "Declaration access can be weaker" inspection in IntelliJ Settings > Inspections.
-ut
