### ISSUE TITLE
How to avoid UnsupportedOperationException: Unsupported for entities with a non-null key

### ISSUE THREAD

**Issue by NightSkyDev** [greenrobot/greenDAO#534]
I'm new to greenDAO and giving it a try again with the 3.0 update using the annotations.  (Nice upgrade btw!)  I'm going through the Getting Started documentation and added the @Entity tag to a model and specifying the @ID, which is a long.  

I see a comment in Issue #511 (java.lang.UnsupportedOperationException: Unsupported for entities with a non-null key) which states the problem is because the ID is a primitive long instead of a Long class, but it doesn't answer why it's happening.  

According to the "Modelling entities" page (http://greenrobot.org/greendao/documentation/modelling-entities/):
"The @Id annotation selects a long/ Long property as the entity ID. In database terms, it’s the primary key. "

It seems a "long" is acceptable?  If so, how do I resolve the auto-generated code using the "hasKey()" which is causing the exception?

It seems what I'm doing is pretty basic, but is there a better way?

Thanks!

**Comment by NightSkyDev** [comment]
Closed this since I'm no longer trying out the library and don't want to waste anyone's time responding.

**Comment by greenrobot-team** [comment]
For reference: When using `Long` with `@Id(autoincrement = true)` greenDAO creates a new key for you when inserting. When using `long` your are responsible for setting the correct key before inserting. Otherwise it will remain at the default value `0`.

So, `hasKey()` does not make sense when using `long` as the key can never be `null`/not exist. -ut
