### ISSUE TITLE
About autoincreament feature for field id

### ISSUE THREAD

**Issue by wintergoes** [greenrobot/greenDAO#553]
When I use following code,
`public class User {`
`    @Id(autoincrement = true)`
`    private long id;`
`}`

After insert data, the id does not auto increment, and gave an error of not unique id. When I change long to Long, it works, anyone who happened this case?

**Comment by igorvilela28** [comment]
that's because in Java, primitive types as attributes in classes get default values, as you can see [here](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html). 

So when you use ```long``` your id is getting the value 0 all the time, and thus you are trying to insert an object that have the same id.

**Comment by greenrobot-team** [comment]
Thanks @igorvilela28 for helping out! Closing then. -ut
