### ISSUE TITLE
List<List<String>> Converter

### ISSUE THREAD

**Issue by giuseppefranco** [greenrobot/greenDAO#576]
Hi, 
How should I handle the customType List<List<String>>.
For example:
``
times: [
[ "Ma-Pe", "10.00-14.00" ],
[ "La", "-" ],
[ "Su", "-" ]
]
``

**Comment by greenrobot-team** [comment]
You will have to find a way to [map it to one of the supported data types](http://greenrobot.org/greendao/documentation/custom-types/).

Otherwise this looks like a good candidate for a [to-one relation](http://greenrobot.org/greendao/documentation/relations/): extract the list elements to a new entity, like `Time`. Then have a `List<Time>` in your current entity. -ut

**Comment by giuseppefranco** [comment]
I used a different approach:

public class ArrayListConverter implements PropertyConverter<List<List<String>>, String> {
    @Override
    public List<List<String>> convertToEntityProperty(String databaseValue) {
        if (databaseValue == null) {
            return null;
        } else {
            return (List<List<String>>)fromJson(databaseValue, new TypeToken<List<List<String>>>() {}.getType());
        }
    }

    @Override
    public String convertToDatabaseValue(List<List<String>> entityProperty) {
        if (entityProperty == null) {
            return null;
        } else {
            return new Gson().toJson(entityProperty);
        }
    }

    private static Object fromJson(String jsonString, Type type) {
        return new Gson().fromJson(jsonString, type);
    }
}
