### ISSUE TITLE
Failed when Jenkins build

### ISSUE THREAD

**Issue by siokagami** [greenrobot/greenDAO#593]
i build my application with Jenkins ,but it failed with this error 
`java:6: error: cannot find symbol`
it can't find the DaoMaster and DaoSession in build/generated/source/greendao
it's no problem,when i use android studio ,but in Jenkins it was failed.
i try some solution in other issue,but it doesn't works?
how to solve it？

**Comment by greenrobot-team** [comment]
Code generation by the greenDAO plugin should be triggered as part of the Gradle Android build process. I am not too familiar with Jenkins, so not sure I can help here. -ut

**Comment by AnswerZhao** [comment]
@siokagami The same issue comes to me, how do you resolve it ? Thx.

**Comment by carlpoole** [comment]
I am currently having this issue also. In Android Studio and running from ./gradlew on my local machine it generates DaoMaster and DaoSession in a **subdirectory** inside the generated **app/build/generated/source/greendao** directory, but on the Jenkins server when I run the gradlew command there it generates it in **app/build/generated/source/greendao** directory. So far I cannot see why. I will update if I find the solution.

**Comment by carlpoole** [comment]
Just a quick update. I found out that my issue was caused by the fact that I refactored code within my model entities folder using the Refactor -> Move tool. I had moved a couple of Entities around and GreenDAO decided to generate my DaoSession and DaoMaster inside one of the subdirectories. I noticed that as I moved Entities around, it moved to a different subdirectory.

In the end what I did was make sure all my `@Entity` classes were in the main entities folder, and then I moved them back into subdirectories using the Refactor -> Move tool for organization purposes, and then it fixed the build. I pushed to my repo and Jenkins ran, and then it worked. I am not sure if this is a bug with GreenDAO specifically.
