### ISSUE TITLE
can't use lambda expressions, build project failed! 

### ISSUE THREAD

**Issue by MoonlightSW** [greenrobot/greenDAO#696]
I'm ensure my JDK version is 1.8, and use retrolambda plug-in

I create a new class and named DeviceCenter ,than project build failed!

I just can't use lambda expressions in class "DeviceCenter" , others is normal.

why?

**Comment by MoonlightSW** [comment]
"org.greenrobot.greendao.annotation.NotNull"

that why my project build failed, please close this problem

**Comment by greenrobot-team** [comment]
If I understand correctly you are using the [Java 8 support](https://developer.android.com/studio/preview/features/java8-support.html) in the [Android Gradle Plugin 3.0.0 preview](https://developer.android.com/studio/preview/features/new-android-plugin.html)?

It does [not support retrolambda](https://developer.android.com/studio/preview/features/new-android-plugin.html#known_issues), maybe that is the issue?

Otherwise can you give a complete error message?
-ut

**Comment by MoonlightSW** [comment]
@greenrobot-team Sorry it's my mistake, DeviceCenter isn't a javabean class(@Entity), I want to check some param (NULLCHECK) , Android Studio auto improt "org.greenrobot.greendao.annotation.NotNull"
make this mistake

**Comment by greenrobot-team** [comment]
Closing this then.
