### ISSUE TITLE
Update record based on oid (string)

### ISSUE THREAD

**Issue by defaultbr** [greenrobot/greenDAO#719]
Hello, i saw some postssaying to use Long id with another key(as index and unique), if i understood correctly, this will update based on another field(not id based) or more, my class:

```
@Entity(nameInDb = "tbl_company")
public class Company {

    @Id(autoincrement = true)
    private Long company_id;

    @Index(unique = true)
    @SerializedName(value = "oid")
    public String oid;
....
```

the exception:

`UNIQUE constraint failed: tbl_company.OID`

of course i understand why this happens, but the doubt is WHY people say this should work to update the row with index/unique based in this configurations.

info: https://github.com/greenrobot/greenDAO/issues/645
info: https://github.com/greenrobot/greenDAO/issues/712
info: https://github.com/greenrobot/greenDAO/issues/645#issuecomment-293260385

so tried with:

```
@Entity(nameInDb = "tbl_company",indexes = {
        @Index(value = "oid", unique = true)}
)
public class Company {

    @Id(autoincrement = true)
    private Long company_id;

    @SerializedName(value = "oid")
    public String oid;
```

error: `Cannot update entity without key - was it inserted before?`

of course i understand it too, i should set the id too, but the information come from server

both i tested with: 

```
.update
.update
.updateInTx
.insertOrReplace
.insertOrReplaceInTx
```

i know i can query for oid to check if its exist, but i was trying to just use updateInTx for many objects at once. Using the query approach i should iterate and check for each one, get id, set id on new and than update, maybe this can impact the performance (sometimes server can return at least 500 items to iterate)

is there a really a way to update the row using another field rather than ID or im doing wrong?  (i dont care about the id, just the oid is important and must be unique and can be updated)

anyway, thank you so much, awesome libs greenrobot provide for us =)

**Comment by greenrobot-team** [comment]
Made a small example like your original entity (`@Index(unique=true)` on a `String` property) to test this: After inserting the entity will get assigned the next available id as expected. Note: all of this is standard SQLite behavior.

To update it you need to set the assigned (row) id before calling `update()`. This requires querying it from the database. You only have to set the properties that have changed.
```java
Author author = authorDao.queryBuilder()
        .where(AuthorDao.Properties.UserId.eq("author1"))
        .unique();
// update properties...
authorDao.update(author);
```

Or you can use `insertOrReplace()` which will delete the existing entity from the database, then insert the new entry. This requires re-setting any properties you want to keep. Internally this uses [SQLite conflict resolution](https://sqlite.org/lang_conflict.html) (`INSERT OR REPLACE` == `INSERT ON CONFLICT REPLACE`).
```java
Author author = new Author();
author.setUserId("author1");
// set properties...
authorDao.insertOrReplace(author);
```

I suppose if you are concerned about performance that much, it would make sense to use raw SQLite (like update with where statement) instead of an ORM.
-ut

**Comment by greenrobot-team** [comment]
Thumbs up. Closing. -ut
