### ISSUE TITLE
ToMany without reference

### ISSUE THREAD

**Issue by cazador4** [greenrobot/greenDAO#748]
Hi guys, 
I just want to know if is it possible to add a relation with no reference in Order.

In docs

```
@Entity
public class Customer {
    @Id private Long id;
 
    @ToMany(referencedJoinProperty = "customerId")
    @OrderBy("date ASC")
    private List<Order> orders;
}
 
@Entity
public class Order {
    @Id private Long id;
    private Date date;
    private long customerId;
}

```

I need to do something like this, because I don't want that an order knows customer:

```
@Entity
public class Customer {
    @Id private Long id;
    @ToMany(referencedJoinProperty = "id")  //<--- (?)
    @OrderBy("date ASC")
    private List<Order> orders;
}
 
@Entity
public class Order {
    @Id private Long id;
    private Date date;
}
```

Thanks!

**Comment by greenrobot-team** [comment]
That is not possible. An Order row (or in greenDAO terms an Order object) needs to have a reference to a Customer row/object. Otherwise how is the database to know which customer an order belongs to?

Using your suggestion the order ID has to be equal to the referenced customer ID. So there can only ever be one order per customer.

Have a look at the [Relations documentation](http://greenrobot.org/greendao/documentation/relations/). There is also a good article called [SQL for Beginners](https://code.tutsplus.com/articles/sql-for-beginners-part-3-database-relationships--net-8561) which explains relations in relational databases. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
