### ISSUE TITLE
Possible cache bug

### ISSUE THREAD

**Issue by qsxs** [greenrobot/greenDAO#757]
我有一个字段
```
@Transient
private boolean isSelected = false;
```
Dao.loadAll()之后修改了这个字段的值，再次Dao.loadAll()或取到的值是上次修改的值。

_Edit to add translation:_
I have a field
```
@Transient
private boolean isSelected = false;
```
Dao.loadAll() then modify the value of this field, again Dao.loadAll() or take the value is the last modified value.

**Comment by yangqing0314** [comment]
Is your the two queries are not in the same thread?

**Comment by greenrobot-team** [comment]
Yes, this is probably due to [the greenDAO session cache](http://greenrobot.org/greendao/documentation/sessions/) which does not re-create objects when they were already loaded from the database.

You may possibly fix this by [clearing the identity scope](http://greenrobot.org/greendao/documentation/sessions/#Clear_the_identity_scope).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
