### ISSUE TITLE
bug with com.android.tools.build:gradle:3.5.0

### ISSUE THREAD

**Issue by TokenYc** [greenrobot/greenDAO#988]
when i use com.android.tools.build:gradle:3.5.0 ,get error 
```
org.greenrobot.greendao.DaoException: Could not init DAOConfig
```
3.4.2 is ok

**Comment by michal-luszczuk** [comment]
Hello,

We also faced this issue after update to `AGP 3.5.0`.
This is related to proguard/D8 rules. 

I noticed that its because of `-keep class **$Properties` line (which was before in GreenDao documentation). To AGP version 3.4.2 this line keeps all generated `**$Properties` classes and also all it's static members. Buf from AGP 3.5.0 all class members are removed.

**Change your line to `-keep class **$Properties {*;}`.**
This will prevent proguard/D8 to remove members of those Properties classes - this should resolve your issue.

**Comment by TokenYc** [comment]
@michal-luszczuk 
thanks,

it works for me.

**Comment by ZheGuangZeng** [comment]
Meet The Same Issue, Maybe Update the doc about this issue is better!

**Comment by PostLiu** [comment]
> Hello,
> 
> We also faced this issue after update to `AGP 3.5.0`.
> This is related to proguard/D8 rules.
> 
> I noticed that its because of `-keep class **$Properties` line (which was before in GreenDao documentation). To AGP version 3.4.2 this line keeps all generated `**$Properties` classes and also all it's static members. Buf from AGP 3.5.0 all class members are removed.
> 
> **Change your line to `-keep class **$Properties {*;}`.**
> This will prevent proguard/D8 to remove members of those Properties classes - this should resolve your issue.

Thank you for your explanation, it works fine.

**Comment by lhj1079947827** [comment]
Thank you. Solved my problem

**Comment by PostLiu** [comment]
> 你好，
> 
> 更新至后，我们也面临这个问题`AGP 3.5.0`。
> 这与proguard / D8规则有关。
> 
> 我注意到这是因为`-keep class **$Properties`行（这在GreenDao文档中之前）。对于AGP 3.4.2版，此行保留所有生成的`**$Properties`类及其所有静态成员。从AGP 3.5.0中删除所有班级成员。
> 
> **将行更改为`-keep class **$Properties {*;}`。**
> 这样可以防止proguard / D8删除那些Properties类的成员-这应该可以解决您的问题。

我也遇到了同样的问题,更新了gradle到最新版也是导致这个问题
